[기능] 오브제 API 연결 및 디자인 수정
100-hours-a-week/10-team-joytas-dao-fe pull request #47
Opened 2024-08-21 13:03 UTC by yoouung

## 📝 개요

- 오브제 조회/수정/ 삭제 API 연결

## ✨ 변경 사항

- 코드나 기능의 주요 변경 사항을 설명합니다.

  - ✨ 오브제 조회 api 연결
  - ✨ 오브제 수정 api 연결
  - ✨ 오브제 삭제 api 연결
  - ✨ 오브제 생성자만 수정/삭제 권한 제공
  - ✨ 유저 목업 데이터 생성

## ℹ️ 참고 사항

- ❗️ 유저 목록, 오브제 뷰어 목록, 채팅 미리보기 연결 추가 필요
- ❗️오브제 생성 버튼 클릭 시 유효성 검사 추가
- ❗️오브제 삭제 후 페이지 이동할 라운지 ID 설정

2024-08-21 15:51 UTC, erica0321 requested changes
백틱 + 얼리리턴 등 한번 확인해주세욥

2024-08-21 15:51 UTC, erica0321 commented on src/pages/objet/ObjetDetail.tsx
> +      const response = await fetch(APIs.objet + '/' + objetId, {
`` 사용하는 거로 바꿔주세욥!
`${APIs.objet}/${objetId}`

2024-08-21 15:51 UTC, erica0321 commented on src/pages/objet/ObjetDetail.tsx
> +      const response = await fetch(APIs.objet + '/' + objetId, {
여기도 백틱!

2024-08-21 15:51 UTC, erica0321 commented on src/pages/objet/UpdateObjet.tsx
> +      const response = await fetch(APIs.objet + `/${objetId}`, {
여기도 백틱

2024-08-21 15:51 UTC, erica0321 commented on src/pages/objet/ObjetDetail.tsx
> +      {isLoading ? (
early return 해주세효

2024-08-21 15:51 UTC, erica0321 commented on src/pages/objet/UpdateObjet.tsx
> +      const response = await fetch(APIs.objet + '/' + objetId, {
여기도 백틱

2024-08-21 15:51 UTC, erica0321 commented on src/pages/objet/UpdateObjet.tsx
> +    }
여기도 else 문 축해서 에러메시지 복구하는 로직 추가해야할 것 같습니답

2024-08-21 16:30 UTC, yoouung commented on src/pages/objet/UpdateObjet.tsx
> +    }
sharedMembers를 제외한 name, description, image는 각각 onChange 함수에서 유효성 검사하기 때문에 버튼 클릭 시에는 따로 안넣어도 될 것 같다고 생각했습니다

2024-08-22 00:14 UTC, erica0321 approved these changes
goooood

2024-08-22 00:14 UTC, erica0321 commented on src/pages/objet/UpdateObjet.tsx
> +    }
네엡

2024-08-22 00:14 UTC, merged